### ISSUE TITLE
**Time Commitment.** As a core committer, I would like an agreement with my organization on my time commitment to the CC program, in order to establish clear expectations upfront on my time allocations.

### ISSUE THREAD

**Issue by nasthagiri** [openedx/open-edx-proposals#172]
**Next Steps**

- [x] Everyone provides asynchronous input on this issue
- [x] @antoviaque and others develop a concrete proposal for review
- [ ] (Optional) Have a synchronous meeting to resolve any open issues
- [ ] Publish decision

**Comment by antoviaque** [comment]
How should we go at this? Maybe we could write some sort of public pledge, where we show support for the Open edX project and the core committer program, and promise to reserve X hours per month of each core committer in our organizations for contributions? This way this would be both something valuable for the project, and for the image of the organizations participating?

**Comment by regisb** [comment]
I'm not sure how I feel about this. As I am my own boss, I don't have to deal with permissions, but does it really make sense for me to have a time commitment to the CC program? I do not believe that the responsibilities that I assume should translate in a fixed time commitment. Instead, if I were an employee, these new responsibilities would have to be explicitly mentioned in my contract to my organization. It would then become *my* responsibility to make sure that I allocate enough time to the CC program.

What would it look like if every employee should count the number of hours allocated to each task they are responsible for? Something along the lines of : "I pledge to dedicate 5h/week on code reviews; 10h/week on feature development and debugging; 5h/week on training my fellow workers; etc." This would be a bit childish (IMHO). Instead, the role of the organization is to make sure that the responsibilities of every employee are clearly defined and that they are consistent with their work capacity.

That's my 0.02€, but maybe I'm just a French socialist :stuck_out_tongue:

**Comment by antoviaque** [comment]
@regisb The goal isn't to dictate precisely how much time each core committer would dedicate to core committer duties -- but rather to ensure that a core committer is provided *at least* that amount of time to work on it, as a way to make it easier to obtain the proper time to work on it from their organization. Otherwise it's easy to end up in a situation where the organization says "fulfill the core committer duties", but then there is always some more urgent duty coming up on a daily basis, and at the end of the month there ended up having very little time available for it in practice. 

You're lucky to be your own boss, so you can set your own timing and priorities - but for most people, having a clear agreement for a minimal number of hours that one is allowed to dedicate to priorities that don't necessarily align with the organization's own priorities makes it much easier to claim that time.

**Comment by kdmccormick** [comment]
@regisb @antoviaque

Personally, I'd like CCs/champions to feel empowered to set aside time for the program in whatever way works for them. That could be:
* designating a number of total hours to spend on the program,
* aiming to spend a certain proportion of the work week on the program,
* committing to a set of goals, or
* really anything else that works for them.

Some may find counting hours childish or counterproductive, and others may find it to be a liberating way of knowing when to put down some other "high-priority" task in favor of longer-term work like this. So, to each their own.

The crux here is that we need to get each of our respective managers/organizations/selves to support that commitment. If we can do that and then be vocal about that support, it may encourage other Open edX organizations to do the same.

If anything, this task strikes me less about _holding ourselves accountable to the program_ as it does _holding our organizations accountable to supporting the program with employee resources_. And this goes for edX just as much as it does any other organization.

**Comment by kdmccormick** [comment]
(I also realize that some members of the program may not have this problem at all. But by vocalizing the time they're able to spend, maybe they help the rest of us advocate to our bosses that we should be afforded more time to focus on the CC program).

**Comment by idegtiarov** [comment]
I like the idea of time commitment and support @kdmccormick thoughts.

Time is always lack and prioritization is a challenge. CCer activities would always lose in that battle with organizations' projects unless we do not have a commitment that at some point would rise program priority higher than everything else.

In a perfect world, I would say we don't need it though under the pressure of reality my words would let it be.

**Comment by nasthagiri** [comment]
@antoviaque At this point, does it make sense to have a deadline for input from each CC's organization?  After which, we can determine the logistics of where CC's goals and commitments are published. (We used the [wiki in Phase 1](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1685291740/Core+Committers+Phase+1+Goals).)

**Comment by antoviaque** [comment]
@nasthagiri Good idea to set a deadline for providing input. Given the holidays, maybe by the end of January? This way it gives everyone a chance to see it here when coming back in the new year, and we can remind everyone during the next community meetup?

To draft the commitment, the wiki sounds good. I have an action item on my side, from the last meetup, to draft a declaration of commitment - besides setting the goals themselves, putting it out as an open letter could help with the visibility of those requirements.

**Comment by antoviaque** [comment]
@nasthagiri @regisb @kdmccormick @idegtiarov To keep moving things forward, and in order to facilitate discussions by reviewing something concrete, I have written a draft of a formal declaration of commitment: https://openedx.atlassian.net/wiki/spaces/COMM/pages/2235957346/Declaration+of+Commitment+to+the+Core+Committer+Program+Draft -- have a look and maybe comment inline there?

I have tried to take into account the points made above - rather than specifying one specific type of commitment for everyone, like a number of hours, it lets each signatory determine its own pledge. I've also focused on organizations, rather than individuals, for the [reasons I gave above](https://github.com/edx/open-edx-proposals/issues/172#issuecomment-738894477) - but we could easily also list individuals who aren't part of a specific organization.

Also, I've tried to put a note, towards the end, to try to encourage educational institutions to also join. So far with the exception of @pdpinch 's MIT, the organizations interested in the program have been mostly technical providers. Given that universities are often the ones who have missing features they would like to see in the platform, it could be good to get them to join this too. And seeing that other universities do it, that could motivate others to look into it too...

Let me know what you think? I have also put a point in the [next Contributors Meetup](https://discuss.openedx.org/t/open-edx-contributors-meetup/1450/37)'s agenda about this, so it would be useful to read it before. :)

CC @felipemontoya @nedbat @sambapete @OmarIthawi @bradenmacdonald @arbrandes

**Comment by regisb** [comment]
I like the idea of having a formal declaration of commitment where each contributor can be free to describe in which manner they pledge to contribute to the program. As a non-native English speaker I'm not too sure the wording is the best, but it's good enough for me. :+1: LGTM :)

**Comment by OmarIthawi** [comment]
I like the idea of letting contributors specify what they commit to. Apart from that, LGTM!

**Comment by kdmccormick** [comment]
Thanks @antoviaque ; looking good to me. The only line I would take issue with is this:

> We are honored to be trusted this way, and the community as a whole is forever in debt for it. It is a debt that we can only repay by doing our utmost to demonstrate its worth. 

The trust certainly must be bidirectional--many of you folks trusted edX by contributing to and building business around the platform. So, if there is any debt, I imagine it is bi-directional too. That is, if the community owes edX meaningful contributions, then edX owes the community proper developer support and a voice in the platform's direction.

I plan on asking my manager sign the pledge so that I (and edX) can be held accountable to supporting the program.

**Comment by antoviaque** [comment]
@kdmccormick 

> The trust certainly must be bidirectional--many of you folks trusted edX by contributing to and building business around the platform. So, if there is any debt, I imagine it is bi-directional too. That is, if the community owes edX meaningful contributions, then edX owes the community proper developer support and a voice in the platform's direction.

Thank you for thinking of this, and for saying it :+1: That could actually be a welcome addition to the document, and be a nice sign of collaboration and common vision. If you feel like making an edit for it, please feel free to :)

**Comment by nasthagiri** [comment]
@antoviaque Thank you for writing this declaration! I added a few comments on the wiki for you to consider.

Once you have reviewed and resolved those comments, are we ready to transition the doc from a `Draft` state to a `Ready for Signing` state?

If so, we can how the core committers feel about going to their employers and asking for their signatures next week. (This Sunday is the [International Day of Education](https://en.unesco.org/commemorations/educationday), which is marked this year on Monday the 25th! 😄)

**Comment by nasthagiri** [comment]
Also, am I reading what @OmarIthawi and @regisb recommended above correctly?  Are they suggesting also having individual CCs commit their own goals to the project?  If so, perhaps we can do something similar to what we did for Phase 1, where [CCs posted their individual goals](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1685291740/Core+Committers+Phase+1+Goals).

**Comment by OmarIthawi** [comment]
@nasthagiri what I meant is that measuring the commitment by capacity may not help my team to give their best contribution to the community.

For example we maintain Figures which is very demanding and that comes at the cost of giving core repositories attention. So our commitment as a provider may not translate very well in the form of X hours / month.

**Comment by kdmccormick** [comment]
@antoviaque I made some revisions to [the declaration](https://openedx.atlassian.net/wiki/spaces/COMM/pages/2235957346/Declaration+of+Commitment+to+the+Core+Committer+Program+Draft), namely:
* calling out both Core Committers and edX Champions explicitly,
* revising the second paragraph and splitting it into two, and
* bolding the most critical sentences (if you only read the bold text, you get a tl;dr version of the declaration :)

Let me know what you think folks.

**Comment by nasthagiri** [comment]
@kdmccormick My preference is to keep edX Champions out of this declaration.  The purpose of our current set of champions was needed to get through Phases 1 and 2 of the Core Committer program. The plan is to scale this program without needing Core Committers to be blocked by a set of Champions.

**Comment by kdmccormick** [comment]
@nasthagiri Makes sense, I'll revise again later today. I would still like to keep something in there about edX supporting the CCs, but I can remove the mentions of Champions.

**Comment by NicoleKessler** [comment]
@nasthagiri @antoviaque As discussed in today's meeting, I have spoken with Stefania regarding our willingness to commit to the CC program.

We would be very pleased to participate in the program representing Abstract Technology. The hours would be around 6 hours per week, where the areas we would be active in are focused on strengthening and promoting the awareness of Open edX as a product and of the whole community, its work and working groups.

Our work includes and will include in the future the following: 
* Website improvements
* Blog posts and articles
* Pointing out the USP, Features, Benefits, Extensions of the product Open edX 
* Highlighting the difference between edX and Open edX
* Improving the Marketing Materials 
* Community event planning
* Communication and coordination between group members and also between other working groups

**Comment by antoviaque** [comment]
@nasthagiri @kdmccormick Thanks for your edits and comments! I have done a pass - this looks good to me :) :+1: 

@NicoleKessler That's great to hear! :D Thank you for taking a decision on this quickly, and for the commitment itself. 

@nasthagiri Even if marketing core committers are only introduced later, could it make sense to include this commitment on the declaration now, so that Abstract Technology can also be part of the original set of signatories? I'm also fine to wait if you prefer it.

**Comment by kdmccormick** [comment]
I believe this was resolved by: https://openedx.atlassian.net/wiki/spaces/COMM/pages/2235957346/Original+Declaration+of+Commitment+to+the+Core+Committer+Program

and later by: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3216900524/Revised+Declaration+of+Commitment+to+the+Core+Contributor+Program
