### ISSUE TITLE
Update OEP-21: Deprecation and Removal with more date guidance

### ISSUE THREAD

**Issue by robrap** [openedx/open-edx-proposals#333]
The DEPR process serves as both a place to document/communicate deprecation, as well as encouraging the actual removal. However, there are many times where we know what needs to be documented, but there are no known resources or deadlines for removal, and determining a target removal date should not be a blocker.

We use the following in the [how-to for documenting toggles](https://edx.readthedocs.io/projects/edx-toggles/en/latest/how_to/documenting_new_feature_toggles.html):

> If the date is uncertain, add 3-6 months to the creation date.
> * This is not a commitment, but may be used to trigger a conversation about removal.
> * For legacy toggles, it is ok for this date to be in the past.

I'm imagining something similar, but I want to start a conversation here without creating the PR.

**Comment by kdmccormick** [comment]
Thanks for opening this discussion @robrap . I typed out a long comment and then realized it went way beyond the scope of your proposal. So, my short on-topic comment is:

I support adding timeline recommendations, but I recommend phrasing them in terms of releases instead of specific dates. I recommend "after the next release is cut" for small deprecations and "after the following release is cut" for larger ones.

_________________________________________________
And my original rambling ideas are:

* I have always found the idea of "Target Removal" date to be ambiguous. Is it the day that you *can* start removing the code, the day that you *plan* to start removing it, or the date that you *wish* someone would start removing it?
* Using exact dates seems disingenuously granular given how long these issues tend to be open. There is something about exact dates that feels like a promise, even if it's specifically not supposed to be a promise. I've felt silly writing down target dates like "2023-03-01", when I'm only 75% sure that we'll be able to remove the feature in spring 2023 at all!

I think I'd like to see something like:
* Get rid of the "Removal Date" and introduce a "Earliest Release without Feature" and "Target Latest Release with Feature"
* For instance: if the Earliest is "X" and the Target Latest is "Z":
  * Deprecation messaging should be included in release "W"
  * Removal would not be permitted until after "W" release is cut. This would give operators (who are often anxious about DEPR surprises in new release) peace of mind that they do not need to update their instance/forks until "X" at the earliest.
  * Removal would be targeted for completion by the release of "Z". When we're regularly missing these targets, we should look at what the project could be doing better to ensure continuous removal of unused code.
* A recommended default would be to set Earliest to one release *after* the next release that will be cut following the feature's Deprecation date, and set Latest to one release after that.
  * For example:
    * Let's say I proposed a DEPR in 2022-03-15 with an Acceptance date of 2022-04-15.
    * I note that the Nutmeg cut is coming up on 2022-04-09, so my feature would first be marked Deprecated in Olive.
    * So, I would set my "Earliest Release without Feature" to "Poplar"
    * and I would set "Target Latest Release with Feature" to "Q*"
  * This recommendation might be overkill in some cases. I would be OK having a recommendation for compressed timeline for smaller DEPRs.

**Comment by kdmccormick** [comment]
> I wonder if "Earliest Release without Feature" is good enough for most tickets. Additional nuance could go in documentation, rather than fields.

This is a good point.

> On a related note, while we were reviewing temporary toggles in a DEPR WG meeting, I was wondering if we could have people create a DEPR ticket as part of creating any "temporary" toggle. The question is how to make this super simple, especially for cases where the expectation is to remove it before it even hits a named release, but to create the ticket for the many cases where clean-up is postponed or forgotten.

Great idea. To remove as much friction as possible, maybe we could make a "Toggle DEPR" issue template, based on the DEPR template but tailored for the case of a short-lived toggle.

> Also, I wonder if the DEPR template could include duplication of some of the most relevant releases and dates, or point to a page that is more quickly usable for DEPR creation. I know I didn't even find the name "Poplar" when I created my ticket.

Definitely something we can do! GH issue templates [let you specify "dropdown" as a field type](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). We could have a dropdown containing the upcoming release cut dates, as well as a "Custom Date" fallback option.

**Comment by kdmccormick** [comment]
Wondering aloud again... this ticket made me realize that what constitutes a large vs medium vs small DEPR isn't something we provide guidance on, even though it's intuitive to a lot of us. Maybe a scoring matrix like this would be helpful to include in the OEP:

### Criteria

#### Migration Prospect
* Full Replacement (+0 points): A documented, drop-in replacement exists with feature parity.
* Partial Replacement (+1 point): A documented replacement exists, but some features are missing or significantly different.
* No Replacement (+2 points)

#### Migration Scope
* Code & Toggles (+0 points): API clients or configuration overrides may need updating, but that's it.
* Data & Infrastructure (+1 points): In addition to the above... Site operators may need to perform special database migrations or spin up new services. Content authors and instructors may need to adapt their content.
* End-user experience (+2 points): In addition to the above...  Content authors and instructors may need to switch to new workflows. Learners may notice a significant change in their experience.

#### Adjustments
* "This feature is so old that we cannot find anyone who uses it": -1 point
* "This 'feature' was always undefined behavior and/or it relies on a bug": -1 point

### Scores & Recommendations
* 0 points = **Trivial.** No need to use the DEPR process. Just announce the change in the forums and the release notes.
  * Example: Renaming some Django settings.
* 1 point = **Low-impact.** Use the DEPR process, but removal can happen right after acceptance.
  * Example: Dropping legacy tables.
* 2 points = **Moderate-impact.** Allow at least one release to go by before remove the feature.
  * Example: Removing redundant tags from the OLX schema.
* 3+ points = **High-impact.** Allow 2+ releases to go by before removing the feature. Consult the Product WG as well.
  * Example: Removing legacy courseware in favor of the MFE (3pts)
  * Hypothetical example: Removing in-course notes (4pts)

**Comment by robrap** [comment]
@kdmccormick: Interesting thoughts. I wonder if you want to start a different issue? It’s related, but possibly much larger in scope to work out the details.

Also, I think it would be better to have a simple DEPR ticket process for some tickets, rather than skipping. This way all relevant details can be captured up front, and if clean-up gets forgotten or delayed, we don’t lose the context.

**Comment by robrap** [comment]
@kdmccormick: I like the idea of a toggle DEPR template. Especially because we have additional data we’d like to capture, like the equivalent logic to keep after the toggle is removed (True or False).

**Comment by davidjoy** [comment]
So a team at 2U is starting work on making an MFE for Learner Dashboard.  As a way of finding a concrete use case and creating bias for action on this, I'm wondering if we could pilot some of this release-based DEPR messaging and communication with them.  

I expect this is a "3" on @kdmccormick 's scoring matrix. 😀

**Comment by robrap** [comment]
@kdmccormick @davidjoy: Thanks for your thoughts. I'd like to rein in and land a decision around dates in this PR. Let's move any other brainstorming ideas to their own ticket(s) (see below).

First, the following are the current DEPR template fields that I would like to clarify/simplify.
* Ticket Acceptance Date
* Technology Removal Date
* First Open edX Named Release Without This Functionality

Summarized proposal from above:
* Remove "Technology Removal Date".
* Replace "First" with "Earliest" in "First Open edX Named Release Without This Functionality", and explain purpose of the field. [Note: I'm not sure if this field already changed, and what it was when I opened this ticket.]
  * Provide a dropdown that includes releases with cut dates, with a "Custom Date" fallback option.

Proposal for "Ticket Acceptance Date":
* Rename to "Target Ticket Acceptance Date"
* Update template description from:
> When is the target date for getting this proposal accepted?
* To:
> When is the target date for getting this proposal reviewed and accepted? A good default is approximately 2 weeks from when the ticket is communicated (see OEP-41).

Note: The 2 week approximate comes from the image in the OEP.

Lastly, @kdmccormick, if you wish, can you create a separate issue (or issues) for any ideas you want to pull from: https://github.com/openedx/open-edx-proposals/issues/333#issuecomment-1149272680. I want that to be a separate proposal to help land this one. Thanks!

**Comment by dianakhuang** [comment]
@robrap DEPR WG talked about this and agree with your proposal.

Next steps:
- update OEP
- update DEPR template

**Comment by robrap** [comment]
The above ticket was closed, and replaced by this PR: https://github.com/openedx/.github/pull/25

**Comment by robrap** [comment]
This work has been completed.
