### ISSUE TITLE
Reword OEP-1 to be from a 3rd-person, role-agnostic point of view

### ISSUE THREAD

**Issue by kdmccormick** [openedx/open-edx-proposals#429]
* Currently OEP-1 is very author-centric; uses "you" a lot (in reference to the OEP author)
* Should instead describe the process from a third-person point of view
* Separate "role responsibility" section should exist for each role, linking out to relevant parts of the process

**Comment by kdmccormick** [comment]
Unassigning myself as I have no current plans to do this.

**Comment by sarina** [comment]
I don't know if I agree on this. Why should this be written in a 3rd party voice? What problem exists because the word "you" is used?

The way that "you" is used is approachable to me and I can follow it. eg this line:

> If you’re not sure who would make a good Arbiter, you should reach out to the [Architecture Group](https://docs.openedx.org/projects/openedx-proposals/en/latest/processes/oep-0001.html#architecture-group); please feel free to participate in the discussion and help choose an arbiter you feel you can work with.

Would it really be better for it to say "The Architecture Group should be leveraged when the authors of a new OEP are not sure who would make a good arbiter. When starting a conversation, authors should participate in the discussion so that the chosen arbiter is one they feel they can work with" ? I don't see what the removal of "you" added except a couple backflips in my mind to finagle this sentence into 3rd party voice.

**Comment by sarina** [comment]
> Separate "role responsibility" section should exist for each role, linking out to relevant parts of the process

What roles exist beyond Author(s) and Arbiter?

**Comment by kdmccormick** [comment]
I don't exactly remember what I was concerned about out with this issue. I agree with you that rewording those sections from 2nd to 3rd person would just make them harder to read.
